/**
 * Transformer-derived data types for the API client.
 * This file is normally regenerated by the dev server when you use transformers on routes.
 */

/// <reference path="./manifest.d.ts" />

export namespace Data {}
