/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Config: () => import('#controllers/config_controller'),
  Health: () => import('#controllers/health_controller'),
  Jobs: () => import('#controllers/jobs_controller'),
  Metrics: () => import('#controllers/metrics_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Queue: () => import('#controllers/queue_controller'),
}
