/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class JobResultSchema extends BaseModel {
  static $columns = ['cpuUsage', 'endedAt', 'exitCode', 'jobId', 'jobResults', 'nodeIp', 'podName', 'ramUsage', 'retryCount', 'runtimeMs', 'startedAt', 'terminationCause'] as const
  $columns = JobResultSchema.$columns
  @column()
  declare cpuUsage: number | null
  @column.dateTime()
  declare endedAt: DateTime | null
  @column()
  declare exitCode: number | null
  @column({ isPrimary: true })
  declare jobId: bigint | number
  @column()
  declare jobResults: any | null
  @column()
  declare nodeIp: string | null
  @column()
  declare podName: string | null
  @column()
  declare ramUsage: bigint | number | null
  @column()
  declare retryCount: number
  @column()
  declare runtimeMs: number | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare terminationCause: string | null
}

export class SubmittedJobSchema extends BaseModel {
  static $columns = ['createdAt', 'estimatedServiceTime', 'jobId', 'priority', 'status', 'submissionId', 'workerImage'] as const
  $columns = SubmittedJobSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estimatedServiceTime: number
  @column({ isPrimary: true })
  declare jobId: bigint | number
  @column()
  declare priority: number
  @column()
  declare status: any
  @column()
  declare submissionId: bigint | number
  @column()
  declare workerImage: string
}
