apiVersion: v1
kind: ConfigMap
metadata:
  name: webcat-config
  namespace: webcat
data:
  NODE_ENV: production
  PORT: "3333"
  HOST: "0.0.0.0"
  LOG_LEVEL: info
  DB_CONNECTION: pg
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: webcat
  SUBMISSIONS_PATH: /data/submissions
  SESSION_DRIVER: cookie
  APP_URL: http://webcat-api-service.webcat.svc.cluster.local:3333
  K8S_NAMESPACE: webcat
  K8S_SUBMISSIONS_ROOT: /data/submissions
  K8S_OUTPUT_ROOT: /data/submissions
  USE_K8S_MOCK: "false"
